env:
  node: true
  es6: true
  jest: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - '!.*'
  - 'node_modules/**/*'
  - '**/*.js'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2022
  sourceType: module
  project:
    - './tsconfig.json'

plugins:
  - jest
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
