name: Set up Beat Saber
description: Fetch Beat Saber bindings and dependencies.
author: nicoco007
branding:
  icon: download
  color: gray-dark
inputs:
  access-token:
    description: Token used to download bindings
    required: true
  path:
    description: Where to unpack dependencies
    required: true
    default: ${{ runner.temp }}\BeatSaberReferenceAssemblies # it is VERY IMPORTANT that this be a backslash or else ResolveAssemblyReferences will not recognize it properly as a TargetFrameworkDirectory
  aliases:
    description: Dictionary of dependency ID aliases
    required: true
    default: '{}'
  game-version:
    description: Game version to use (overrides game version from manifest)
    required: false
  additional-dependencies:
    description: Additional dependencies required for build but not at runtime (e.g. optional dependencies)
    required: true
    default: '{}'
  project-path:
    description: 'The path to the project (csproj file) that will be built.'
    required: true
  project-configuration:
    description: 'The configuration to use when fetching properties from the project. Defaults to `Release`.'
    required: true
    default: 'Release'
runs:
  using: node20
  main: dist/index.js
