name: Download Beatmods Dependencies
description: Download and extract dependencies from beatmods using manifest.json
author: Goobwabber
branding:
  icon: download
  color: gray-dark
inputs:
  manifest:
    description: Path to manifest.json
    required: false
    default: ${{github.workspace}}/manifest.json
  path:
    description: Where to unpack dependencies
    required: false
    default: ${{github.workspace}}/Refs
  aliases:
    description: Dictionary of dependency id aliases
    required: false
    default: '{}'
  game-version:
    description: Game version to use (overrides game version from manifest)
    required: false
  additional-dependencies:
    description: Additional dependencies required for build but not at runtime (e.g. optional dependencies)
    required: false
    default: '{}'
runs:
  using: node16
  main: dist/index.js
