name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - name: Download Dependencies
        uses: ./
        with:
          manifest: ./examplemanifest.json
      - name: Download Fake Dependencies
        uses: ./
        with:
          manifest: ./missingmanifest.json