name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Real-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Dependencies
        uses: ./
        with:
          manifest: ./tests/realmanifest.json
  Fake-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Dependencies
        uses: ./
        with:
          manifest: ./tests/fakemanifest.json
  Aliased-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Dependencies
        uses: ./
        with: 
          manifest: ./tests/aliasedmanifest.json
          aliases: '{"CustomAvatar": "Custom Avatars"}'
  BOM-Encoding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Dependencies
        uses: ./
        with:
          manifest: ./tests/bommanifest.json