name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Dependencies
        uses: ./
        with:
          manifest: ./examplemanifest.json
  missingtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Dependencies
        uses: ./
        with:
          manifest: ./missingmanifest.json